# =============================================================================
# hml — workload layer
#
# This layer reads the foundation layer's outputs through terraform_remote_state,
# so it needs to know where that state lives. Everything else is declared here
# explicitly; the root variables carry no defaults.
# =============================================================================

# --- Region -------------------------------------------------------------------
region = "us-east-1"

# --- Foundation state ---------------------------------------------------------
# Where to read the foundation layer's outputs from. Must match the bucket and key
# in foundation/environments/hml/backend.hcl, or this layer silently reads a
# different environment's cluster.
foundation_state_bucket = "eks-development-tfstate-889384902110"
foundation_state_key    = "foundation/hml/terraform.tfstate"

# --- Chart versions -----------------------------------------------------------
# Pinned, not defaulted: an unpinned chart means a rebuild can install a different
# Argo CD than the one that was reviewed.
argocd_chart_version = "10.4.0"

# --- Storage ------------------------------------------------------------------
# Delete here, Retain in production. hml is torn down and rebuilt between
# sessions, and a retained volume outlives `terraform destroy` — it is left in
# Released state, outside Terraform's knowledge, and keeps billing. Over enough
# cycles those orphans accumulate silently.
#
# The data in this environment is disposable by definition, so the protection
# Retain buys is worth nothing here and the cleanup it costs is worth avoiding.
storage_reclaim_policy = "Delete"

# --- GitOps -------------------------------------------------------------------
# The root Application tracks this repository; the platform AppProject accepts no
# other source. Tracking a branch means Argo follows every commit — acceptable in
# hml, where a bad sync is cheap to fix.
platform_repo_url      = "https://github.com/gulinux86/platform-gitops"
platform_repo_revision = "main"

# Declared before the repository exists, so the boundary is written first.
apps_repo_url = "https://github.com/gulinux86/app-gitops"

# Prefix glob: a new application needs no Terraform change, and system namespaces
# stay out of reach because they do not match.
apps_namespaces = ["app-*"]

# Chart repositories count as sources. A multi-source Application pulls its chart
# from one and its values from another, and Argo CD checks both — listing only the
# Git repository fails every chart-based component with "repo is not permitted".
platform_source_repos = [
  "https://github.com/gulinux86/platform-gitops",
  "https://github.com/kubernetes-sigs/gateway-api",
  "https://charts.jetstack.io",
  "https://istio-release.storage.googleapis.com/charts",

  # Karpenter ships as an OCI artifact rather than from an HTTP chart repository.
  # Argo CD checks the scheme-qualified URL against this list exactly as it does a
  # Git or HTTPS source, so omitting it fails the Application with "repo is not
  # permitted" — the failure PR #31 exists to fix, from a different registry.
  "oci://public.ecr.aws/karpenter/karpenter",
]

apps_source_repos = ["https://github.com/gulinux86/app-gitops"]

# --- Platform ingress ---------------------------------------------------------
# These name a Service that this repository does not create. It is generated by
# istiod from the Gateway in platform-gitops (components/examples/gateway.yaml),
# and Istio derives the Service name from the Gateway's: `<gateway>-istio`.
#
# Nothing fails loudly on a mismatch. The TargetGroupBinding resolves to nothing,
# the target group stays empty, and the load balancer answers 503 — so when traffic
# does not arrive, read target health before reading logs.
gateway_namespace    = "istio-ingress"
gateway_service_name = "platform-gateway-istio"

# The Gateway's HTTP listener. Plain HTTP while the load balancer is internal;
# TLS terminates here when the external path lands.
ingress_listener_port = 80
